<?php
// Palestras da Hotmart (do arquivo txt)
return [
    '10 anos traduzindo de tudo. Minha carreira na VICE Brasil',
    '20 termos de negócios e finanças que todo tradutor deve conhecer',
    'A Era da Informação (sob controle)',
    'A IA e o mundo da tradução',
    'A Língua Inglesa e os textos para negócios',
    'A Sétima Maravilha das Organizações Internacionais',
    'A Tradulação de Krazy Kat e Otros Kuadrinhos Komplicados (sic)',
    'A Tradução Financeira com Dinaura Julles',
    'A Tradução para a dublagem brasileira',
    'A arte da alta produtividade Insights para empresários, profissionais liberais e autônomos',
    'A cabeça do tradutor de russo: O processo de tradução de um clássico da ficção científica',
    'A comunicação intercultural pelos olhos de uma intérprete de japonês',
    'A culinária em legendas',
    'A gênese da tradução da obra The Scandals of Translation, de Lawrence Venuti',
    'A importância da inteligência emocional na rotina do profissional autônomo — Shirlei Correa',
    'A importância das ferramentas digitais para a tradução — Valter Mendes JR.',
    'A importância do networking para o tradutor',
    'A importância dos Guias de Estilo na tradução',
    'A interpretação consecutiva e outras práticas que te tornam um melhor intérprete de simultânea',
    'A legendagem na publicidade: particularidades e novas tendências',
    'A linguagem LGBTQIA+ na tradução para dublagem',
    'A naturalidade e o tradutor do futuro',
    'A tradutora roqueira: livros, música e interação com os leitores',
    'A tradução da animação (Des)encanto: muitos aprendizados (e um pouco de rebeldia)',
    'A tradução de obras audiovisuais derivadas na era transmídia: E agora, tradutor?',
    'A tradução literária hoje: desafios de entrada, permanência e viabilidade',
    'A tradução para dublagem de Time Patrol Bon',
    'AMA (Ask me anything) sobre localização de jogos!',
    'Abordagem a agências pelo LinkedIn',
    'Achados de uma mentoria: o que aprendemos ensinando tradução literária',
    'Afinal, o que é gramática? — Amanda Moura',
    'Alegrias e desafios de se traduzir Monteiro Lobato',
    'Alongamentos',
    'Amigos, amigos, trabalhos à parte: o trabalho com colegas contratantes',
    'Aposte no visual!',
    'Arquivar, organizar e traduzir',
    'Arquivar, organizar e traduzir — Any Marry',
    'As escolhas do gerente de projetos',
    'As novas práticas de legendagem com o avanço do streaming',
    'As palavras e nossa mitologia pessoal',
    'Ask Me Anything about Interpretainment',
    'Ask me anything sobre legendagem',
    'Assim diz a legenda',
    'Audiodescrição de Cinema de Terror',
    'Audiodescrição rima com tradução de muitas maneiras além da sonoridade',
    'Aula prática de tradução/localização de texto de turismo e viagem',
    'Autogestão para tradutores',
    'Aventuras de uma equipe brasileira no LocJam Made in Italy',
    'Born to be global — A importância da tradução de SEO',
    'Burnout e o trabalho autônomo',
    'CAT Tools e Machine Translations: discutindo a relação',
    'CULT-Estácio — A importância da especialização na tradução da área médica',
    'CULT-Estácio — Como se especializar em tradução audiovisual',
    'CULT-Estácio — Localização em marketing: mais do que apenas criatividade',
    'CULT-Estácio — Tradução de textos da área médica: uma receita de sucesso',
    'Cadê o original que estava aqui? Quando uma tradutora se torna copywriter',
    'Caminhos da Tradução na graduação em Letras',
    'Carteira qualificada',
    'Cinco tipos diferentes de tradução',
    'Closed Caption: legenda com emoção',
    'Cobrança e negociação para tradutores',
    'Como a dramaturgia influencia a tradução audiovisual',
    'Como a tecnologia facilita a vida do tradutor',
    'Como aprimorar sua carreira na tradução com o voluntariado — Karen Tkaczyk e Catherine Christaki',
    'Como cobrar uma tradução',
    'Como conciliar as carreiras de tradutor e intérprete',
    'Como fazer para sempre lembrar dos termos nas suas línguas? — Denise Araujo',
    'Como planejar uma boa aposentadoria',
    'Como se preparar para um apocalipse zumbi',
    'Como simplificar seu inglês na tradução técnica',
    'Como sua mãe já dizia: você não é todo mundo',
    'Como traduzir a Terra-média',
    'Como traduzir sem perder tempo com pesquisas — Ascanio Roquette',
    'Como usar ferramentas de corpus para dar mais naturalidade ao seu texto',
    'Como é o credenciamento para intérpretes na UE: requisitos e a prova',
    'Como é que traduz essa porr@? — Renato Geraldes e Evelise Scapol',
    'Comunicação Acessível: Estratégias para integrar a acessibilidade a teatro, redes sociais, palestras e outras formas de diálogo',
    'Condições que devemos exigir para a interpretação remota',
    'Conhecimento é poder',
    'Construindo uma carreira de alto nível na interpretação',
    'Contra o terraplanismo linguístico na tradução',
    'Controle financeiro e a relação cliente-contador',
    'Criatividade de milhões, automatismo de centavos',
    'Cuidados com face, ombros, braços e mãos',
    'Curso SDL Studio — Parte 1',
    'Curso SDL Studio — Parte 2',
    'Curso SDL Studio — Parte 3 — Intermediário',
    'Da Paraíba para o mundo: legendagem de curtas-metragens paraibanos',
    'Da boca para o texto escrito',
    'Da tendência à palavra: uma introdução à tradução de moda',
    'Da tradução à versão: novos desafios para uma tradutora emigrante',
    'De férias com o tradutor: Os desafios da tradução de reality shows',
    'De intérprete infantil oficial da família a intérprete profissional!',
    'De tradutora literária a escritora',
    'Desafios ao traduzir um artigo científico do inglês indiano ao português',
    'Desafios da tradução',
    'Desafios e percalços de tradutores iniciantes nas agências de tradução',
    'Desvendando o Proz',
    'Dica de pausa',
    'Dica sobre uso de celular',
    'Dicas para otimizar o seu processo de revisão',
    'Dicionário Gastronômico: receita e degustação',
    'Direitos autorais para tradutores',
    'Do Sul do Brasil ao Norte da América do Norte: como internacionalizei minha carreira no Canadá',
    'Do laudo à bula: a variedade de textos na tradução médica',
    'Dos livros lidos aos livros traduzidos',
    'EULA: usando a internet a nosso favor',
    'Em busca da naturalidade',
    'Ensaio sobre a curiosidade: como os verbos errar, aprender e mudar devem ser um mantra',
    'Enshittification: ou como nos acostumamos à degradação das plataformas online',
    'Entendendo a tributação',
    'Equipamentos e RSI: o que fazer, o que não fazer, quando chorar',
    'Erros recorrentes em revisão e técnicas para solucioná-los',
    'Especial ITD 2020 — Lançamento do PED4TI — Gilson Mattos',
    'Especial ITD 2020 — Mais organização e produtividade? Tecnologia é a resposta! — Fernanda Rocha',
    'Especial ITD 2020 — Marketing pessoal e negociação para tradutores — André Ribeiro',
    'Especial ITD 2020 — O mundo não te odeia — Kelly Elizeu',
    'Especial ITD 2020 — O tradutor para dublagem, o texto traduzido e o estúdio — Paulo Noriega',
    'Especial ITD 2020 — T101 explica SDL Studio — SDL-Babel',
    'Especial ITD 2020 — T101 explica WordFast — Daniel Estill',
    'Especial ITD 2020 — T101 explica XBench — Mitsue Siqueira',
    'Especial ITD 2020 — T101 explica memoQ — Val Ivonica',
    'Especial ITD 2020 — Tradução científica: trajetória, especialização e peculiaridades — Laurieny e Marina',
    'Esports e jogos digitais competitivos — O que são, por que são importantes e casos de tradução e interpretação',
    'Exemplos práticos de multiculturalismo na tradução de inglês e português',
    'Exorcize o seu texto: acabe com os possuídos!',
    'Experiência com tradução jurídica do gênero contrato',
    'FAQ de tradutores sobre finanças e investimentos',
    'Falando das pedras no caminho na tradução de ficção',
    'Falando de tradução para localização (apps, softwares, sites)',
    'Falsos cognatos e decalques na tradução médica inglês>português',
    'Ficção histórica: tudo serve para alguma coisa',
    'Filhos e Carreira: lições e dicas de tradutores e intérpretes',
    'Financeiro é a mãe: a ciência por trás do \"na volta a gente compra\"',
    'Formação e mercado no par italiano-português',
    'Fotografia em casa',
    'Gerativismo: A gramática que está escondida no nosso subconsciente',
    'Gerentes de projeto: os maestros do setor de tradução e localização',
    'Gestão Financeira: Planejamento, administração e gestão do dinheiro',
    'Gestão de renda',
    'Golpes: é possível se prevenir? — Francine Oliveira',
    'Hacks de interpretação e minha experiência com interpretação na sede do governo',
    'I\'ve Known Rivers - A tradução e o mercado editorial sob a perspectiva negra',
    'Indo além da tradução: novos caminhos e oportunidades para profissionais do texto',
    'Interação humano-computador na tradução: dos benefícios aos desafios',
    'Interpretando Altas Autoridades',
    'Interpretação Comunitária: um instrumento de acesso a direitos fundamentais — Mylene Queiroz e Jaqueline Nordin',
    'Interpretação Espanhol-Português e a Tecnologia!',
    'Interpretação de auditorias e acompanhamento',
    'Interpretação de texto e tradução',
    'Interpretação no Oscar',
    'Interpretação religiosa: the good, the bad and the ugly',
    'Interpretação: a vida real',
    'Inventar o trabalho dos outros?',
    'Italiano e português: tão parecidos e tão diferentes',
    'Jogo de palavras: localização de jogos de tabuleiro',
    'Jon Fosse no Brasil: A tradução de É a Ales',
    'Jornalismo e tradução: tão íntimos e tão estranhos',
    'Jurídico e ciência na interpretação de noticiário',
    'Kit de sobrevivência: Vinte dicas pra se manter na tradução — Andressa Gatto',
    'LBM Week — LBM Academy: A Escola das Ratarias da tradução audiovisual',
    'LBM Week — Lengendagem: Estudo de caso de "As golpistas"',
    'LBM Week — Pequenas empresas de TAV, grandes negócios',
    'LBM Week — TAV+PÓS: Estudo de caso de "Fronteiras do pensamento"',
    'Language Lead? Que bicho é esse?',
    'Langue x Parole: uma discussão dicotômica "nesSAUSSUREa"',
    'Legenda automática: a vilã da vez',
    'Legendagem em inglês: estudo de caso de "Olhar de cão"',
    'Legendagem em tempo real feita por estenotipia com tradução simultânea',
    'Legendagem especializada: foco no gênero institucional',
    'Legendagem: Descomplicando a Sincronia no Subtitle Edit',
    'Les casquettes du monde littéraire : navegando entre a criação e a tradução do texto',
    'Linguagem inclusiva: gênero, política e linguagem — Ana Elisa Ribeiro',
    'Linguagem neutra: a aplicação e seus desafios',
    'Linguística e Tradução: entre tapas e beijos — Meritxell Almarza',
    'LinkedIn — Parte 1',
    'LinkedIn — Parte 2',
    'Linux para tradutores',
    'Lista de agências',
    'Literatura para a vida',
    'Live sobre normas — Normas ISO/NBR para Tradução e Interpretação: e agora?',
    'LocJAM - Soluções "PraVer"',
    'Localização + SEO = Sites que agradam o Google',
    'Localização de games: linguagem e mídia',
    'Localização de jogos de tabuleiro',
    'Línguas de trabalho: o que são e como mantê-las afiadas',
    'Línguas estrangeiras + negócios + tecnologia = tradução e interpretação',
    'MTPE: Exemplos práticos de Machine Translation Post Editing',
    'Mais de 10 maneiras de traduzir provérbios e expressões idiomáticas',
    'Maratona — Congresso não é só palestra; tenha uma mente empresária',
    'Maratona — Negociação avançada — Palestra atualizada',
    'Maratona — Os melhores clientes esperam por você no LinkedIn',
    'Maratona — Transcriação (tradução criativa) — O que os clientes realmente querem do tradutor',
    'Marketing pessoal',
    'Masterclass Inteligência Artificial em 2024',
    'Meditação — Aula de meditação — Sofia Pulici',
    'Melhores práticas de LQA: um Fail diz tudo?',
    'Mentoring: A ferramenta para conseguir uma carreira em tradução',
    'Mercado de trabalho: Teoria e prática',
    'Mesa sobre interpretação — PUC-Rio',
    'Mesa sobre tradução — PUC-Rio',
    'Minha (nenhuma) tradução é perfeita. Como aprender com a preparação de texto',
    'Montando passo a passo uma macro no Word',
    'Máquinas, política e futebol: traduzindo do alemão',
    'Negociação avançada',
    'Norma linguística e tradução - o que é traduzir para o português brasileiro?',
    'Notas: muito além dos símbolos',
    'O Diário de Mika acessível em libras — Juliana Fernandes',
    'O Jeito que a Gente Diz: em busca da naturalidade',
    'O Skill Set do intérprete — Marcelle Castro',
    'O culto à pobreza na tradução',
    'O fantástico mundo da pesquisa clínica',
    'O gênero neutro está presente. E você, está no Presente ou no passado?',
    'O método Starbucks aplicado ao mundo da tradução',
    'O nascimento e o renascimento da literatura traduzida',
    'O novo mercado de tradução: a revolução da inteligência artificial',
    'O papel da revisão na tradução',
    'O papel dos revisores na produção de livros didáticos',
    'O papel vital de comunicação do revisor',
    'O que leva a uma carreira bem-sucedida na tradução?',
    'O que é e como funciona uma boutique de tradução jurídica',
    'O tradutor nômade digital',
    'O tradutor profissional e a globalização',
    'Oficina de CNV',
    'Oficina de tradução de HQs',
    'Organizando sua vida financeira',
    'Organizando suas contas',
    'Os 10 da tradução literária - Parte 1',
    'Os 10 da tradução literária - Parte 2',
    'Os desafios da interpretação nos eventos esportivos',
    'Os desafios da produção editorial de best-sellers',
    'Os desafios na tradução de Uma mulher estranha, de Leylâ Erbil',
    'Os intérpretes e a tecnologia',
    'Os paralelos entre o trabalho do tradutor dos serviços de inteligência e o do tradutor freelancer',
    'PDI: Plano de Desenvolvimento Individual — Parte 1',
    'PDI: Plano de Desenvolvimento Individual — Parte 2',
    'Para (não) audaciosos: por uma Poética do Traduzir',
    'Per Aspera Ad Astra: a tradução de High Frontier 4 All',
    'Percy Jackson e a adaptação na tradução intersemiótica do livro para a tela',
    'Perdido ou cantando a caminho do banco? Como anda você na profissão um ano depois do mundo mudar?',
    'Perspectivas da carreira do tradutor com a IA',
    'Por que preciso pensar sobre racismo se não sou racista?',
    'Portuguese into English? Brasileiros podem fazer versões de qualidade para o inglês?',
    'Posicionamento do monitor',
    'Postura profissional de um tradutor',
    'Precisamos falar sobre investimentos',
    'Preparação de texto, que bicho é esse?',
    'Primeiros passos na tradução literária',
    'ProZ KudoZ além dos Pontos: Perspectivas e Possibilidades',
    'Produtividade',
    'Profissão tradutor/intérprete de Libras - trajetórias e formação',
    'Prospecção de Clientes, Networking e Marketing Pessoal para Tradutores Introvertidos',
    'Prática de movimentos conscientes — Sofia Pulici',
    'Qual é a dimensão do mundo do tradutor?',
    'Qualidade da tradução na era da revolução tecnológica',
    'Qualificações e possibilidades para o profissional pós-editor',
    'Quality Assurance no cliente: o outro lado da mesa',
    'Quanto vale meu trabalho?',
    'Que tal aprender como fazer seu próprio glossário?',
    'Que tempo bom, que não volta nunca mais',
    'Quem está certo? A eterna batalha entre revisão e tradução',
    'RSI 3 anos depois do fim do mundo: um balanço',
    'Rebranding: como se reinventar – sem reinventar a roda',
    'Reflexões sobre a criação de recursos visuais a partir de conteúdos textuais',
    'Regex for dummies: como começar a usar expressões regulares',
    'Respiração consciente — Prática de respiração consciente — Sofia Pulici',
    'Rock\'n roll x livros (histórias+idiomas+mistura cultural) ideias = tradutora literária',
    'S07E37 — Ivar Junior, Horacio Corral, Luciana Boldorini',
    'S07E40 — Tort Law e os casos mais bizarros dos EUA',
    'S07E41 — Robson Ortlibas',
    'S07E42 — Cátia Santana, Denise Delegá, Horacio Corral e Patrícia Gimenez',
    'S07E43 — Giovana Boselli',
    'S07E44 — Núbia Tropéia',
    'S07E45 — Jéssica Gubert e Raul Rocha',
    'S07E46 — Stella Tagnin',
    'S07E47 — Diego Marsicano',
    'S07E48 — Carolina Bisson',
    'S07E49 — Daniel Guidi',
    'S07E50 — William Cruz',
    'S07E51 — Luigi, Marco e Rafael',
    'S08E01 — Karìne Souto',
    'S08E02 — Marcus Mangetti',
    'S08E03 — Jean Trindade',
    'S08E04 — Bruna Beatriz',
    'S08E05 — Joacyr Oliveira',
    'S08E06 — Simone Brito',
    'S08E07 — Matheus Fabris',
    'S08E08 — Luiza Levy e Renato Geraldes',
    'S08E09 — Val Ivonica',
    'S08E10 — Ivar Jr e Horacio Corral',
    'S08E11 — Marina Araujo',
    'S08E12 — Jerusa Marreti',
    'S08E13 — Dinaura Julles',
    'S08E14 — Luiza Brahemcha',
    'S08E15 — Luciana Bonancio',
    'S08E16 — Michel Teixeira',
    'S08E17 — Sátia Marini',
    'S08E18 — Bruna Andrade',
    'S08E19 — Valter Mendes',
    'S08E20 — Manuela Sampaio',
    'S08E26 — Vanessa Thiago',
    'S08E29 — Ivar Jr',
    'SDL Studio: primeiros passos',
    'She-ra e as Princesas do Poder',
    'Singularidades da tradução de idiomas raros',
    'Small step or giant leap?',
    'Sprechen Sie Deutsch? Dois tradutores brasileiros na Alemanha',
    'Só assisto legendado x Dublado é muito melhor',
    'Sua amiga, a tradução automática',
    'Síndrome do Impostor',
    'TQAuditor grátis para tradutores',
    'Tempos verbais e suas especificidades nas versões de artigos científicos para o inglês',
    'Terças da Cultura I — Isa Mara Lando',
    'Terças da Cultura II — Isa Mara Lando',
    'Terças da Cultura III — Isa Mara Lando',
    'Terças da Cultura IV — Isa Mara Lando',
    'Terças da Cultura V — Isa Mara Lando',
    'Termos de negócios e finanças que todo tradutor deve conhecer',
    'Tradutor como empreendedor: da criação de marca ao relacionamento com o cliente',
    'Tradutor: um eterno aprendiz',
    'Tradutores euprendedores e o relacionamento com o cliente',
    'Tradutores formados, informados e desenformados. Nossos muitos caminhos',
    'Tradutores juramentados: mitos e verdades',
    'Traduttore, traditore e manipolatore - uma palestra em português brasileiro — Letícia Sallorenzo',
    'Traduzindo Clássicos',
    'Traduzindo Neil Gaiman e outras criaturas fantásticas',
    'Traduzindo jogos de tabuleiro',
    'Traduzindo marketing',
    'Traduzindo para a cena',
    'Traduzindo um relatório do século XVIII sobre vampiros',
    'Traduzir Machado de Assis: causos e percalços do Bruxo além-fronteiras',
    'Traduzir RPG é sempre um desafio',
    'Tradução X Versão Brasileira: diferenças e importância do seu texto no dia a dia dos profissionais de dublagem — Leo Pinheiro',
    'Tradução animal! Uma ou duas coisinhas que você precisa saber antes de se aventurar nos textos de medicina veterinária',
    'Tradução automática na tradução técnica: testamos uma abordagem',
    'Tradução criativa na localização de jogos',
    'Tradução de games? É muito simples! #sqn',
    'Tradução de histórias em quadrinhos e o mercado mainstream no Brasil',
    'Tradução de jogos — O mercado brasileiro',
    'Tradução de literatura infantil e infanto-juvenil: un plus a mais',
    'Tradução de musicais',
    'Tradução de patentes: por onde começar?',
    'Tradução de textos de turismo e viagem: características e teoria funcionalista',
    'Tradução de videogames: o ponto de vista do tradutor',
    'Tradução e edição de literatura especulativa: estudo de casos',
    'Tradução em Direitos Humanos: oportunidades e desafios',
    'Tradução jornalística, muito além das palavras',
    'Tradução no esporte ou esporte na tradução?',
    'Tradução para dublagem',
    'Tradução para dublagem de cinema',
    'Tradução para dublagem de língua turca',
    'Tradução pública: como era e como ficou após a nova legislação',
    'Tradução técnica: recursos e desafios',
    'Transcreation 101',
    'Translation and Interpreting in the USA',
    'Travessia Tradutória',
    'Treine como um atleta 2: mais dicas para o tradutor autodidata',
    'Treine como um atleta: dicas para o tradutor autodidata',
    'Tudo que eu posso dizer sobre tradução audiovisual sem quebrar nenhum sigilo',
    'Técnicas de pesquisa para tradutores — Raphael Corrêa',
    'UTF? ANSI? O que são codificações de texto',
    'Um passeio pela construção da literatura norte-americana',
    'Uma porta para grandes oportunidades',
    'Variantes linguísticas: com que roupa eu vou?',
    'Vivendo da tradução em Portugal',
    'What the heck! A internacionalização da Dona Hermínia',
    'Who they are: Estratégias de tradução do gênero não binário',
    'Às voltas com a Babel": profissionalizando a gestão de uma empresa',
    'É possível distinguir a tradução automática da tradução humana?',
    'É rir para não chorar: Os desafios da tradução do humor na dublagem',
    'É um livro? É um jogo? É uma HQ? A localização de livros-jogos e seus desafios'
];
?>