<?php
// --- 1. Configuração e Dados ---
if (session_status() === PHP_SESSION_NONE) session_start();
require_once __DIR__ . '/../config/database.php';
require_once __DIR__ . '/../config/dash_database.php';
require_once __DIR__ . '/../config/dash_functions.php';

if (!isLoggedIn()) { header('Location: /login.php'); exit; }

$user_id = $_SESSION['user_id'];
$invoice_id = $_GET['id'] ?? 0;
$lang = $_GET['lang'] ?? 'pt'; // Padrão Português

// Busca Dados
$stmt = $pdo->prepare("SELECT i.*, c.company, c.contact_name, c.email, c.country, c.phone, u.name as user_name, u.email as user_email 
                       FROM dash_invoices i 
                       LEFT JOIN dash_clients c ON i.client_id = c.id 
                       LEFT JOIN users u ON i.user_id = u.id
                       WHERE i.id = ? AND i.user_id = ?");
$stmt->execute([$invoice_id, $user_id]);
$invoice = $stmt->fetch(PDO::FETCH_ASSOC);

if (!$invoice) die("Fatura não encontrada.");

$stmtItems = $pdo->prepare("SELECT * FROM dash_invoice_items WHERE invoice_id = ?");
$stmtItems->execute([$invoice_id]);
$items = $stmtItems->fetchAll(PDO::FETCH_ASSOC);

// --- 2. Dicionário de Tradução ---
$t = [
    'pt' => [
        'invoice' => 'FATURA', 'date' => 'Data de Emissão', 'due' => 'Data de Vencimento', 
        'to' => 'Faturado para', 'from' => 'De', 'desc' => 'Descrição', 'qty' => 'Qtd', 
        'price' => 'Preço Unit.', 'total' => 'Total', 'notes' => 'Observações',
        'footer' => 'Gerada pelo Dash-T101, da Translators101', 'page' => 'Página'
    ],
    'en' => [
        'invoice' => 'INVOICE', 'date' => 'Issue Date', 'due' => 'Due Date', 
        'to' => 'Bill To', 'from' => 'From', 'desc' => 'Description', 'qty' => 'Qty', 
        'price' => 'Unit Price', 'total' => 'Total', 'notes' => 'Notes',
        'footer' => 'Generated by Dash-T101, from Translators101', 'page' => 'Page'
    ],
    'es' => [
        'invoice' => 'FACTURA', 'date' => 'Fecha de Emisión', 'due' => 'Fecha de Vencimiento', 
        'to' => 'Facturado a', 'from' => 'De', 'desc' => 'Descripción', 'qty' => 'Cant.', 
        'price' => 'Precio Unit.', 'total' => 'Total', 'notes' => 'Notas',
        'footer' => 'Generada por Dash-T101, de Translators101', 'page' => 'Página'
    ]
];
$txt = $t[$lang] ?? $t['pt'];

// --- 3. Formatação de Dados ---
// Sanitizar nome para arquivo
$filename = sprintf(
    "Invoice nº %s - %s - %s.pdf", 
    $invoice['number'], 
    preg_replace('/[^a-zA-Z0-9 ]/', '', $invoice['company']), 
    preg_replace('/[^a-zA-Z0-9 ]/', '', $invoice['user_name'])
);

// Datas formatadas
$date_issued = date('d/m/Y', strtotime($invoice['date']));
$date_due = date('d/m/Y', strtotime($invoice['due_date']));

// Dispara download automático se solicitado via URL
$auto_download = isset($_GET['download']) && $_GET['download'] == 'true';

$page_title = 'Fatura ' . $invoice['number'];
include __DIR__ . '/../vision/includes/head.php';
include __DIR__ . '/../vision/includes/header.php';
include __DIR__ . '/../vision/includes/sidebar.php';
?>

<script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js"></script>

<style>
    .main-content { padding-bottom: 100px; }
    
    /* Barra de Ações */
    .action-bar {
        display: flex; justify-content: space-between; align-items: center;
        max-width: 210mm; margin: 0 auto 20px auto;
        padding: 10px; background: rgba(255,255,255,0.05); border-radius: 12px;
    }
    .lang-selector {
        display: flex; gap: 5px;
    }
    .lang-btn {
        padding: 5px 10px; border: 1px solid rgba(255,255,255,0.2); border-radius: 6px;
        color: #aaa; text-decoration: none; font-size: 0.85rem; font-weight: 600;
    }
    .lang-btn.active { background: var(--brand-purple); color: #fff; border-color: var(--brand-purple); }
    
    .btn-action {
        padding: 10px 20px; border-radius: 20px; font-weight: 600; color: #fff; text-decoration: none;
        display: inline-flex; align-items: center; gap: 8px; font-size: 0.9rem; cursor: pointer; border: 0;
    }
    .btn-back { background: rgba(255,255,255,0.1); }
    .btn-download { background: linear-gradient(135deg, #7c4dff, #b388ff); box-shadow: 0 4px 15px rgba(124, 77, 255, 0.4); }
    .btn-download:hover { transform: translateY(-2px); }

    /* --- ESTILOS DO PAPEL DA FATURA (Correção de Cores) --- */
    .invoice-paper {
        width: 210mm;
        min-height: 297mm;
        margin: 0 auto;
        background: #ffffff !important; /* Fundo Branco Forçado */
        color: #333333 !important;      /* Texto Escuro Forçado */
        padding: 40px;
        box-shadow: 0 10px 40px rgba(0,0,0,0.3);
        position: relative;
        display: flex;
        flex-direction: column;
    }

    /* Forçar cor preta em tudo dentro do papel para sobrescrever tema escuro */
    .invoice-paper * { color: #333333 !important; border-color: #eeeeee !important; }
    .invoice-paper h1, .invoice-paper h2, .invoice-paper h3, .invoice-paper h4 { color: #111 !important; }
    
    /* Header */
    .inv-header { display: flex; justify-content: space-between; margin-bottom: 50px; border-bottom: 2px solid #f0f0f0 !important; padding-bottom: 20px; }
    .inv-title { font-size: 2.5rem; font-weight: 800; text-transform: uppercase; letter-spacing: 2px; color: #444 !important; }
    .inv-number { font-size: 1rem; color: #666 !important; margin-top: 5px; }
    
    .inv-meta table { text-align: right; border: none !important; }
    .inv-meta td { padding: 2px 0 2px 20px; border: none !important; font-size: 0.9rem; }
    .inv-meta .meta-label { font-weight: 600; color: #555 !important; }

    /* Addresses */
    .inv-addresses { display: flex; justify-content: space-between; margin-bottom: 50px; }
    .addr-box { width: 45%; }
    .addr-title { font-size: 0.85rem; text-transform: uppercase; font-weight: 700; color: #888 !important; margin-bottom: 10px; border-bottom: 1px solid #eee !important; padding-bottom: 5px; }
    .addr-name { font-size: 1.1rem; font-weight: 700; margin-bottom: 5px; }
    .addr-line { font-size: 0.95rem; line-height: 1.4; color: #555 !important; }

    /* Table */
    .inv-table { width: 100%; border-collapse: collapse; margin-bottom: 40px; }
    .inv-table th { text-align: left; padding: 12px 10px; background-color: #f8f9fa !important; font-weight: 700; text-transform: uppercase; font-size: 0.8rem; border-bottom: 2px solid #ddd !important; }
    .inv-table td { padding: 12px 10px; border-bottom: 1px solid #eee !important; font-size: 0.95rem; }
    .text-right { text-align: right; }
    
    /* Total */
    .inv-footer-section { margin-top: auto; /* Empurra para o fim da página */ }
    
    .inv-totals { display: flex; justify-content: flex-end; margin-bottom: 40px; }
    .totals-box { width: 250px; }
    .total-row { display: flex; justify-content: space-between; padding: 5px 0; font-size: 0.9rem; }
    .total-row.final { border-top: 2px solid #333 !important; margin-top: 10px; padding-top: 10px; font-size: 1.2rem; font-weight: 800; }
    
    .inv-notes { margin-bottom: 30px; font-size: 0.9rem; color: #666 !important; background: #fdfdfd !important; padding: 15px; border: 1px solid #eee !important; border-radius: 8px; }
    
    .page-footer {
        border-top: 1px solid #ddd !important;
        padding-top: 15px;
        text-align: center;
        font-size: 0.8rem;
        color: #999 !important;
    }

    /* Responsividade para visualização */
    @media (max-width: 768px) {
        .invoice-paper { width: 100%; min-height: auto; padding: 20px; }
        .inv-header, .inv-addresses { flex-direction: column; gap: 20px; }
        .inv-meta, .addr-box { width: 100%; text-align: left; }
    }
</style>

<div class="main-content">

    <div class="action-bar">
        <a href="projects_list.php" class="btn-action btn-back">
            <i class="fas fa-arrow-left"></i> Voltar
        </a>
        
        <div class="lang-selector">
            <a href="?id=<?php echo $invoice_id; ?>&lang=pt" class="lang-btn <?php echo $lang=='pt'?'active':''; ?>">PT</a>
            <a href="?id=<?php echo $invoice_id; ?>&lang=en" class="lang-btn <?php echo $lang=='en'?'active':''; ?>">EN</a>
            <a href="?id=<?php echo $invoice_id; ?>&lang=es" class="lang-btn <?php echo $lang=='es'?'active':''; ?>">ES</a>
        </div>

        <button onclick="generatePDF()" class="btn-action btn-download">
            <i class="fas fa-file-download"></i> Baixar PDF
        </button>
    </div>

    <div id="invoice-content" class="invoice-paper">
        
        <div class="inv-header">
            <div class="inv-brand">
                <div class="inv-title"><?php echo $txt['invoice']; ?></div>
                <div class="inv-number">#<?php echo $invoice['number']; ?></div>
            </div>
            <div class="inv-meta">
                <table>
                    <tr>
                        <td class="meta-label"><?php echo $txt['date']; ?>:</td>
                        <td><?php echo $date_issued; ?></td>
                    </tr>
                    <tr>
                        <td class="meta-label"><?php echo $txt['due']; ?>:</td>
                        <td><?php echo $date_due; ?></td>
                    </tr>
                </table>
            </div>
        </div>

        <div class="inv-addresses">
            <div class="addr-box">
                <div class="addr-title"><?php echo $txt['from']; ?></div>
                <div class="addr-name"><?php echo htmlspecialchars($invoice['user_name']); ?></div>
                <div class="addr-line"><?php echo htmlspecialchars($invoice['user_email']); ?></div>
                <div class="addr-line">Translators101</div> </div>
            <div class="addr-box" style="text-align: right;">
                <div class="addr-title"><?php echo $txt['to']; ?></div>
                <div class="addr-name"><?php echo htmlspecialchars($invoice['company']); ?></div>
                <?php if($invoice['contact_name']): ?><div class="addr-line"><?php echo htmlspecialchars($invoice['contact_name']); ?></div><?php endif; ?>
                <?php if($invoice['email']): ?><div class="addr-line"><?php echo htmlspecialchars($invoice['email']); ?></div><?php endif; ?>
                <?php if($invoice['country']): ?><div class="addr-line"><?php echo htmlspecialchars($invoice['country']); ?></div><?php endif; ?>
            </div>
        </div>

        <table class="inv-table">
            <thead>
                <tr>
                    <th width="50%"><?php echo $txt['desc']; ?></th>
                    <th width="10%" class="text-right"><?php echo $txt['qty']; ?></th>
                    <th width="20%" class="text-right"><?php echo $txt['price']; ?></th>
                    <th width="20%" class="text-right"><?php echo $txt['total']; ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($items as $item): ?>
                <tr>
                    <td><?php echo htmlspecialchars($item['description']); ?></td>
                    <td class="text-right"><?php echo number_format($item['quantity'], 2, ',', '.'); ?></td>
                    <td class="text-right"><?php echo number_format($item['unit_price'], 2, ',', '.'); ?></td>
                    <td class="text-right"><?php echo number_format($item['total'], 2, ',', '.'); ?></td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>

        <div class="inv-footer-section">
            <div class="inv-totals">
                <div class="totals-box">
                    <div class="total-row final">
                        <span><?php echo $txt['total']; ?></span>
                        <span><?php echo formatCurrency($invoice['total'], $invoice['currency']); ?></span>
                    </div>
                </div>
            </div>

            <?php if ($invoice['notes']): ?>
            <div class="inv-notes">
                <strong><?php echo $txt['notes']; ?>:</strong><br>
                <?php echo nl2br(htmlspecialchars($invoice['notes'])); ?>
            </div>
            <?php endif; ?>

            <div class="page-footer">
                <?php echo $txt['footer']; ?>
            </div>
        </div>

    </div>
</div>

<script>
function generatePDF() {
    const element = document.getElementById('invoice-content');
    const filename = '<?php echo $filename; ?>';

    const opt = {
        margin:       0, // Margem zero pois o CSS #invoice-paper já tem padding
        filename:     filename,
        image:        { type: 'jpeg', quality: 0.98 },
        html2canvas:  { scale: 2, useCORS: true },
        jsPDF:        { unit: 'mm', format: 'a4', orientation: 'portrait' }
    };

    // Botão feedback
    const btn = document.querySelector('.btn-download');
    const originalText = btn.innerHTML;
    btn.innerHTML = '<i class="fas fa-spinner fa-spin"></i> Gerando PDF...';
    btn.disabled = true;

    html2pdf().set(opt).from(element).save().then(() => {
        btn.innerHTML = originalText;
        btn.disabled = false;
    });
}

// Auto-download se vier parâmetro na URL
<?php if ($auto_download): ?>
document.addEventListener('DOMContentLoaded', () => {
    generatePDF();
});
<?php endif; ?>
</script>

<?php include __DIR__ . '/../vision/includes/footer.php'; ?>